import Page from "components/Page/Page";

const PrivacyPolicy = () => {
	return (
		<Page title="Privacy Policy">
			<h1 className="text-2xl lg:text-[32px] font-bold text-dark mb-6">
				Privacy Policy
			</h1>
			<p className="text-sm text-dark mb-6">
				Last updated: August 09, 2022 <br /> This Privacy Policy describes Our
				policies and procedures on the collection, use and disclosure of Your
				information when You use the Service and tells You about Your privacy
				rights and how the law protects You. We use Your Personal data to
				provide and improve the Service. By using the Service, You agree to the
				collection and use of information in accordance with this Privacy
				Policy.
			</p>
			<h2 className="text-dark font-bold mb-6">INTERPRETATION & DEFINITIONS</h2>
			<h3 className="text-dark font-bold mb-6">Interpretation</h3>
			<p className="text-sm text-dark mb-6">
				The words of which the initial letter is capitalized have meanings
				defined under the following conditions. The following definitions shall
				have the same meaning regardless of whether they appear in singular or
				in plural.
			</p>
			<p className="text-sm text-dark mb-6">
				The words of which the initial letter is capitalized have meanings
				defined under the following conditions. The following definitions shall
				have the same meaning regardless of whether they appear in singular or
				in plural.
			</p>
			<h4 className="text-dark font-bold mb-6">Definitions</h4>
			<p className="text-sm text-dark mb-6">
				For the purposes of this Privacy Policy:
			</p>
			<p className="text-sm text-dark mb-6">
				Account means a unique account created for You to access our Service or
				parts of our Service.
			</p>
			<p className="text-sm text-dark mb-6">
				Affiliate means an entity that controls, is controlled by or is under
				common control with a party, where "control" means ownership of 50% or
				more of the shares, equity interest or other securities entitled to vote
				for election of directors or other managing authority.
			</p>
			<p className="text-sm text-dark mb-6">
				Application means the software program provided by the Company
				downloaded by You on any electronic device, named The Accounter
			</p>
			<p className="text-sm text-dark mb-6">
				Company (referred to as either "the Company", "We", "Us" or "Our" in
				this Agreement) refers to The Accounter Technologies Ltd, Dubai.
			</p>
			<p className="text-sm text-dark mb-6">
				Cookies are small files that are placed on Your computer, mobile device
				or any other device by a website, containing the details of Your
				browsing history on that website among its many uses.
			</p>
			<p className="text-sm text-dark mb-6">
				Country refers to: United Arab Emirates
			</p>
			<p className="text-sm text-dark mb-6">
				Device means any device that can access the Service such as a computer,
				a cellphone or a digital tablet.
			</p>
			<p className="text-sm text-dark mb-6">
				Personal Data is any information that relates to an identified or
				identifiable individual.
			</p>
			<p className="text-sm text-dark mb-6">
				Service refers to the Application or the Website or both.
			</p>
			<p className="text-sm text-dark mb-6">
				Service Provider means any natural or legal person who processes the
				data on behalf of the Company. It refers to third-party companies or
				individuals employed by the Company to facilitate the Service, to
				provide the Service on behalf of the Company, to perform services
				related to the Service or to assist the Company in analyzing how the
				Service is used.
			</p>
			<p className="text-sm text-dark mb-6">
				Usage Data refers to data collected automatically, either generated by
				the use of the Service or from the Service infrastructure itself (for
				example, the duration of a page visit).
			</p>
			<p className="text-sm text-dark mb-6">
				Website refers to The Accounter, accessible from
				https://www.theaccounter.com
			</p>
			<p className="text-sm text-dark mb-6">
				You means the individual accessing or using the Service, or the company,
				or other legal entity on behalf of which such individual is accessing or
				using the Service, as applicable.
			</p>
			<h3 className="text-dark font-bold mb-6">
				COLLECTING & USING YOUR PERSONAL DATA
			</h3>
			<h4 className="text-dark font-bold mb-6">Types of Data Collected</h4>
			<h4 className="text-dark font-bold mb-6">Personal Data</h4>
			<p className="text-sm text-dark mb-6">
				While using Our Service, We may ask You to provide Us with certain
				personally identifiable information that can be used to contact or
				identify You. Personally identifiable information may include, but is
				not limited to:
			</p>
			<ul className="list-disc list-inside *:text-sm *:text-dark">
				<li>Email address</li>
				<li>First name and last name</li>
				<li>Phone number</li>
				<li>Address, State, Province, ZIP/Postal code, City</li>
				<li>
					Bank account information in order to pay for products and/or services
					within the Service
				</li>
			</ul>
		</Page>
	);
};

export default PrivacyPolicy;
